vim.keymap.set("n", "<leader>h", vim.lsp.buf.hover)
vim.keymap.set("n", "<leader>d", function()
        vim.lsp.buf.definition({ loclist = true })
    end)
vim.keymap.set("n", "<leader>i", function()
        vim.lsp.buf.implementation({ loclist = true })
    end)
vim.keymap.set("n", "<leader>rf", function()
        vim.lsp.buf.references(nil, { loclist = true })
    end)
vim.keymap.set("n", "<leader>rn", vim.lsp.buf.rename)
vim.keymap.set("n", "<leader>a", vim.lsp.buf.code_action)

